name: main
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: install
        run: make install
      - name: test
        run: make test
      - name: lint
        run: make lint
      - name: test-coverage
        run: make test-coverage
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '20'
    - name: install
      run: make install
    - name: test
      run: make test
    - name: format code coverage
      uses: ./.github/actions/cc-test-reporter
      with:
        subcommand: "format-coverage -t lcov ./coverage/lcov.info"