name: main
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: install
        run: make install
      - name: test
        run: make test
      - name: lint
        run: make lint
      - name: test-coverage
        run: make test-coverage
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: paambaati/codeclimate-action@v5.0.0
      # Add Code Climate secret key
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: make test-coverage
        debug: true