name: main
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: install
        run: make install
      - name: test
        run: make test
      - name: lint
        run: make lint
      - name: test-coverage
        run: make test-coverage
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Code Climate
      uses: remarkablemark/setup-codeclimate@v2
    - name: Run Test and Upload Coverage
      run: |
        cc-test-reporter before-build
        # insert your test command here
        cc-test-reporter after-build --exit-code $?
      env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}