name: main
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: install
        run: make install
      - name: test
        run: make test
      - name: lint
        run: make lint
      - name: test-coverage
        run: make test-coverage
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '20'
    - name: install
      run: make install
    - name: test
      run: make test
    - uses: brokeyourbike/codeclimate-action@v0.1
      with:
        token: ${{ secrets.CC_TEST_REPORTER_ID }}
        files: ./coverage1.xml,./coverage2.xml